name: validation

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      pylint_output: ""
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - name: Rebase from main branch
      uses: cirrus-actions/rebase@1.8
      env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Analysing the code with pylint
      run: |
        echo "pylint_output=$(find . -name '../*.py' -exec pylint {} \; " >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
    - name: CINotify Email
      uses: cinotify/github-action@v1.1.2
      with:
        to: "monika.anand@intel.com"
        subject: "Pylint execution results for latest CJE Automation code are attached with"
        body: echo ${{ env.pylint_output }}
  
    
